language: php
php:
  - '7.1.33'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  - nightly
matrix:
  allow_failures:
    -   php: nightly
install:
  - composer self-update --1
  - composer --version
  - composer install
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "8.0" ]]; then composer require --dev psalm; else composer require --dev psalm@1.1.8; fi
  - ./vendor/bin/psalm
after_script:
  - php vendor/bin/php-coveralls -v
